swagger: "2.0"
info:
  title: "Savood"
  version: "1.0"
  description: "denn nur lebendiges food tut gut"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"


tags:
- name: "users"
  description: "Management of users"
- name: "offerings"
  description: "Management of offered food items"
- name: "messages"
  description: "Operations about users"
- name: "health"
  description: "Operation regarding helath of application"


### PATHS ###
paths:
  /healthcheck:
    get:
      security: []
      operationId: "healthcheckGet"
      tags:
        - "health"
      summary: "Check Server status"
      produces:
        - "application/json"
      responses:
        '200':
          description: Server is healthy
        '503':
          $ref: "#/responses/Unhealthy"
  /feed:
    get:
      operationId: getFeed
      parameters:
        - in: query
          description: Latitude
          name: lat
          required: true
          type: number
        - in: query
          description: Longitude
          name: lon
          required: true
          type: number
        - in: query
          description: Distance in Meters
          name: distance
          required: true
          type: number
      tags:
      - "offerings"
      summary: "Display a feed of nearby offerings"
      produces:
      - "application/json"
      responses:
        '200':
          description: Object found and returned
          schema:
            type: "array"
            items:
              $ref: '#/definitions/Offering'
        '400':
          $ref: '#/responses/InvalidParameterInput'
        '500':
          $ref: '#/responses/ErrorResponse'
  /offerings:
    get:
      operationId: getOfferings
      parameters:
        - in: query
          description: Filteres offerings by owned or requested
          name: filter
          required: false
          type: string
          enum:
            - owned
            - requested
      tags:
      - "offerings"
      summary: "Display owned or requested offerings"
      produces:
      - "application/json"
      responses:
        '200':
          description: Object found and returned
          schema:
            type: "array"
            items:
              $ref: '#/definitions/Offering'
        '400':
          $ref: '#/responses/InvalidParameterInput'
    post:
      operationId: createNewOffering
      tags:
      - "offerings"
      summary: "Add a new offering"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Offering that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Offering"
      responses:
        '200':
          description: Object found and returned
          schema:
            $ref: '#/definitions/Offering'
        '400':
          $ref: '#/responses/InvalidParameterInput'
        '403':
          $ref: '#/responses/Unauthorized'
        '500':
          $ref: '#/responses/ErrorResponse'
  /offerings/{id}:
    parameters:
      - in: path
        required: true
        name: id
        type: string
    get:
      operationId: getOfferingById
      tags:
      - "offerings"
      summary: "Display an offering"
      produces:
      - "application/json"
      responses:
        '200':
          description: Object found and returned
          schema:
            $ref: '#/definitions/Offering'
        '400':
          $ref: '#/responses/InvalidParameterInput'
        '404':
          $ref: '#/responses/NotFound'
        '500':
          $ref: '#/responses/ErrorResponse'
    patch:
      operationId: updateOfferingById
      tags:
      - "offerings"
      summary: "Update an offering"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "New parameters of the offering"
        required: true
        schema:
          $ref: "#/definitions/Offering"
      responses:
        '204':
          description: Accepted; No response.
        '400':
          $ref: '#/responses/InvalidParameterInput'
        '403':
          $ref: '#/responses/ErrorResponse'
        '404':
          $ref: '#/responses/NotFound'
        '500':
          $ref: '#/responses/ErrorResponse'
    delete:
      operationId: deleteOfferingById
      tags:
      - "offerings"
      summary: "Delete an offering"
      produces:
      - "application/json"
      responses:
        '204':
          description: Removed; No response.
        '400':
          $ref: '#/responses/InvalidParameterInput'
        '403':
          $ref: '#/responses/ErrorResponse'
        '500':
          $ref: '#/responses/ErrorResponse'
  /offerings/{id}/image.jpeg:
    parameters:
      - in: path
        required: true
        name: id
        type: string
    post:
      tags:
        - "offerings"
        - "image"
      summary: Uploads avatar image.
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: upfile
          type: file
          description: The file to upload.
      responses:
        '204':
          description: Accepted; No response.
        '400':
          $ref: '#/responses/InvalidParameterInput'
        '403':
          $ref: '#/responses/Unauthorized'
        '500':
          $ref: '#/responses/ErrorResponse'
    get:
      parameters:
        - in: query
          required: false
          name: height
          type: number
          description: If either width or height is set to 0, it will be set to an aspect ratio preserving value.
        - in: query
          required: false
          name: width
          type: number
          description: If either width or height is set to 0, it will be set to an aspect ratio preserving value.
      tags:
        - "offerings"
        - "image"
      summary: Gets the avatar image.
      produces:
        - image/jpeg
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: file
        '404':
          $ref: '#/responses/NotFound'
        '500':
          $ref: '#/responses/ErrorResponse'
  /offerings/{id}/chats:
    parameters:
      - in: path
        required: true
        name: id
        type: string
    get:
      operationId: getAllChatsForOffering
      tags:
        - "offerings"
        - "messages"
      summary: "Display a user"
      produces:
      - "application/json"
      responses:
        '200':
          description: Object found and returned
          schema:
            type: "array"
            items:
              $ref: '#/definitions/Chat'
        '400':
          $ref: '#/responses/InvalidParameterInput'
  /users:
    post:
      operationId: createNewUser
      tags:
      - "users"
      summary: "Add a new user"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        '200':
          description: Object found and returned
          schema:
            $ref: '#/definitions/User'
        '400':
          $ref: '#/responses/InvalidParameterInput'
  /users/{id}:
    parameters:
      - in: path
        required: true
        name: id
        type: string
    get:
      operationId: getUserById
      tags:
      - "users"
      summary: "Display a user"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        '200':
          description: Object found and returned
          schema:
            $ref: '#/definitions/User'
        '400':
          $ref: '#/responses/InvalidParameterInput'
    patch:
      operationId: updateUserById
      tags:
      - "users"
      summary: "Update a user"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "New parameters of the User"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        '204':
          description: Accepted; No response.
        '400':
          $ref: '#/responses/InvalidParameterInput'
    delete:
      operationId: deleteUserById
      tags:
      - "users"
      summary: "Delete a users"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        '204':
          description: Removed; No response.
        '400':
          $ref: '#/responses/InvalidParameterInput'


  /users/{id}/image.jpeg:
    parameters:
      - in: path
        required: true
        name: id
        type: string
    post:
      tags:
        - "users"
        - "image"
      summary: Uploads avatar image.
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: upfile
          type: file
          description: The file to upload.
      responses:
        '204':
          description: Accepted; No response.
        '400':
          $ref: '#/responses/InvalidParameterInput'
        '403':
          $ref: '#/responses/Unauthorized'
        '500':
          $ref: '#/responses/ErrorResponse'
    get:
      tags:
        - "users"
        - "image"
      summary: Gets the avatar image.
      parameters:
        - in: query
          required: false
          name: height
          type: number
          description: If either width or height is set to 0, it will be set to an aspect ratio preserving value.
        - in: query
          required: false
          name: width
          type: number
          description: If either width or height is set to 0, it will be set to an aspect ratio preserving value.
      produces:
        - image/jpeg
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: file
        '404':
          $ref: '#/responses/NotFound'
        '500':
          $ref: '#/responses/ErrorResponse'
  /users/{id}/backgroundimage.jpeg:
    parameters:
      - in: path
        required: true
        name: id
        type: string
    post:
      tags:
        - "users"
        - "image"
      summary: Uploads avatar image.
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: upfile
          type: file
          description: The file to upload.
      responses:
        '204':
          description: Accepted; No response.
        '400':
          $ref: '#/responses/InvalidParameterInput'
        '403':
          $ref: '#/responses/Unauthorized'
        '500':
          $ref: '#/responses/ErrorResponse'
    get:
      tags:
        - "users"
        - "image"
      summary: Gets the avatar image.
      parameters:
        - in: query
          required: false
          name: height
          type: number
          description: If either width or height is set to 0, it will be set to an aspect ratio preserving value.
        - in: query
          required: false
          name: width
          type: number
          description: If either width or height is set to 0, it will be set to an aspect ratio preserving value.
      produces:
        - image/jpeg
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: file
        '404':
          $ref: '#/responses/NotFound'
        '500':
          $ref: '#/responses/ErrorResponse'
  /chats/:
    get:
      operationId: getAllChats
      tags:
      - "messages"
      summary: "Get all Chats"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        '200':
          description: Object found and returned
          schema:
            type: "array"
            items:
              $ref: '#/definitions/Chat'
        '400':
          $ref: '#/responses/InvalidParameterInput'

  /chats/{chatID}/messages:
    parameters:
      - in: path
        required: true
        name: chatID
        type: string
    get:
      operationId: getAllMessagesForChat
      tags:
      - "messages"
      summary: "Add a new message"
      produces:
      - "application/json"
      responses:
        '200':
          description: Object found and returned
          schema:
            type: "array"
            items:
              $ref: '#/definitions/Message'
        '400':
          $ref: '#/responses/InvalidParameterInput'
    post:
      operationId: createNewMessage
      tags:
      - "messages"
      summary: "Add a new message"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Message that needs to be added"
        required: true
        schema:
            $ref: '#/definitions/Message'
      responses:
        '200':
          description: Object found and returned
          schema:
            $ref: '#/definitions/Message'
        '400':
          $ref: '#/responses/InvalidParameterInput'
  /chats/{chatID}/messages/{id}:
    parameters:
      - in: path
        required: true
        name: chatID
        type: string
      - in: path
        required: true
        name: id
        type: string
    get:
      operationId: getMessageById
      tags:
      - "messages"
      summary: "Display a message"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        '200':
          description: Object found and returned
          schema:
            $ref: '#/definitions/Message'
        '400':
          $ref: '#/responses/InvalidParameterInput'
    patch:
      operationId: updateMessageById
      tags:
      - "messages"
      summary: "Update a message"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "New parameters of the message"
        required: true
        schema:
          $ref: "#/definitions/Message"
      responses:
        '204':
          description: Accepted; No response.
        '400':
          $ref: '#/responses/InvalidParameterInput'
    delete:
      operationId: deleteMessageById
      tags:
      - "messages"
      summary: "Delete a message"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        '204':
          description: Removed; No response.
        '400':
          $ref: '#/responses/InvalidParameterInput'
  /placeSavood:
    post:
      operationId: placeSavood
      tags:
      - "rpc-calls"
      - "offerings"
      summary: "Places a savood on an offering"

      parameters:
      - in: query
        name: offeringId
        type: string
        description: The offering ID on which the savood should be placed.
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        '200':
          description: Savood is placed
          schema:
            $ref: '#/definitions/SuccessObject'
        '400':
          $ref: '#/responses/InvalidParameterInput'
        '403':
          $ref: '#/responses/ErrorResponse'
  /unSavood:
    post:
      operationId: unSavood
      tags:
      - "rpc-calls"
      - "offerings"
      summary: "Places a savood on an offering"

      parameters:
      - in: query
        name: offeringId
        type: string
        description: The offering ID on which the savood should be placed.
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        '204':
          description: Savood is deleted
        '400':
          $ref: '#/responses/InvalidParameterInput'
        '403':
          $ref: '#/responses/ErrorResponse'


securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header

security:
  - bearer: []

### RESPONSES ###
responses:
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: "#/definitions/ErrorModel"
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: "#/definitions/ErrorModel"
  ErrorResponse:
    description: "Generic Error"
    schema:
      $ref: "#/definitions/ErrorModel"
  Unhealthy:
    description: Server is unhealthy
    schema:
      $ref: "#/definitions/ErrorModel"
  InvalidParameterInput:
    description: Invalid parameter input was passed
    schema:
      $ref: "#/definitions/InvalidParameterInput"

### DEFINITIONS ###
definitions:
  Address:
    type: "object"
    properties:
        street:
          type: "string"
        number:
          type: "string"
        zip:
          type: "string"
        city:
          type: "string"
  User:
    type: "object"
    properties:
      _id:
        type: "string"
      firstname:
        type: "string"
      lastname:
        type: "string"
      email:
        type: "string"
        format: "email"
      address:
        $ref: '#/definitions/Address'
      phone:
        type: "string"
        format: "phone"
      description:
        type: "string"
      badges:
        type: "array"
        items:
          type: "string"
    xml:
      name: "user"
    example:
      _id: "5"
      firstname: Marty
      lastname: McFlfy
      email: apiteam@swagger.io
      phone: 202-555-0191
      address:
          street: Musterstraße
          number: "1337"
          zip: "42069"
          city: Musterstadt
      avatarId: ''
      backgroundId: ''
      description: I save the wrap and the world
      badges: [
        "SAVOOD_1",
        "SAVOOD_5",
        "SAVOOD_10",
        "MESSAGE_1",
        ]


  UserShort:
    type: "object"
    properties:
      _id:
        type: "string"
      firstname:
        type: "string"
      lastname:
        type: "string"
      badges:
        type: "array"
        items:
          type: "string"
    xml:
      name: "user"
    example:
      _id: "5"
      firstname: Marty
      lastname: McFlfy
      badges: [
        "SAVOOD_1",
        "SAVOOD_5",
        "SAVOOD_10",
        "MESSAGE_1",
        ]
  Message:
    type: "object"
    properties:
      from:
        $ref: "#/definitions/UserShort"
      content:
        type: "string"
      time:
        type: "string"
        format: "date-time"
    xml:
      name: "Message"

  Chat:
    type: "object"
    properties:
      _id:
        type: "string"
      partner:
        $ref: "#/definitions/UserShort"
      offeringId:
        type: "array"
        items:
          type: "string"
    example:
      _id: "17"
      partner:
        _id: "5"
        firstname: Marty
        lastname: McFlfy
      offeringId: [1,2,3,4,5]

  Offering:
    type: "object"
    properties:
      _id:
        type: "string"
      name:
        type: "string"
      description:
        type: "string"
      creator:
        $ref: "#/definitions/UserShort"
      best-by-date:
        type: "string"
        format: "date"
      address:
        $ref: '#/definitions/Address'
      location:
        type: object
        properties:
            type:
                type: string
            coordinates:
                description: longitude then latidue as floats
                type: array
                items:
                    type: number
      requested-by:
        type: "integer"
        format: "int64"
      time:
        type: "string"
        format: "date-time"
      savooded:
        type: "boolean"
    xml:
      name: "Offering"
    example:
      _id: "123"
      name: "Normale Kartoffeln"
      description: "Die Lagen hier so rum, kp mehr von wann, aber was solls. ich brauche Sie nicht mehr. Also nur zu Savooded mich ihr Jünger"
      creator:
        _id: "5"
        firstname: Marty
        lastname: McFlfy
      best-by-date: "2018-06-21"
      requested-by: 12
      time: "2018-06-21T13:55:58.380Z"
      location:
        coordinates: [50.5636277, 9.6711443]
      address:
          street: Musterstraße
          number: "1337"
          zip: "42069"
          city: Musterstadt
      savooded: true
  SuccessObject:
    type: object
    properties:
      success:
        type: boolean

  Principal:
    type: object
    properties:
      email:
        type: string
      userid:
        type: string
  ErrorModel:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  InvalidParameterInput:
    type: object
    properties:
      attribute:
        type: string
      message:
        type: string
    required:
      - attribute
      - message

### UNCOMMENT THIS for codegen
#basePath: /v2/
#schemes:
# - http



### UNCOMMENT THIS for swaggerhub
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /TimMaa/Savood/1.0
schemes:
 - https
 - http